version: ~> 1.0
language: php
php: 8.1.2
os: linux
dist: focal
before_install:
  - echo 'deb [trusted=yes] https://repo.symfony.com/apt/ /' | sudo tee /etc/apt/sources.list.d/symfony-cli.list
  - sudo apt update
  - sudo apt install librabbitmq-dev pecl php-ctype php-bcmath php-ctype php-curl php-intl php-opcache php-pdo php-simplexml php-zip symfony-cli
  - sudo pecl install amqp apcu
install:
  - composer install
  - symfony check:requirements
jobs:
  include:
    - stage: Testing
      script:
        - php -d memory_limit=-1 vendor/bin/phpunit -c config/.phpunit.xml.dist
    -
      script:
        - php -d memory_limit=-1 vendor/bin/psalm -c config/.psalm.xml
    - stage: Quality
      script:
        - php -d memory_limit=-1 vendor/bin/php-cs-fixer fix --config=config/.php_cs.dist.php --dry-run --diff --verbose --allow-risky=yes
# services:
#   - docker
# before_install:
#   - sudo apt remove docker docker-engine docker.io containerd runc
#   - sudo apt update
#   - sudo apt-get install ca-certificates curl gnupg lsb-release
#   - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
#   - echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
#   - sudo apt update
#   - sudo apt install docker-ce docker-ce-cli containerd.io
#   - mkdir -p ~/.docker/cli-plugins/
#   - curl -SL https://github.com/docker/compose/releases/download/v2.2.3/docker-compose-linux-x86_64 -o ~/.docker/cli-plugins/docker-compose
#   - chmod +x ~/.docker/cli-plugins/docker-compose
#   - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
# install:
#   - make install
# jobs:
#   include:
#     - stage: Testing
#       script:
#         - make phpunit
#     -
#       script:
#         - make psalm
#     - stage: Quality
#       script:
#         - make phpcs
