parameters:

services:
  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

  _instanceof:
    Twig\Extension\ExtensionInterface:
      tags: [ twig.extension ]

  App\Shared\:
    resource: '%kernel.project_dir%/src/Shared/'
    exclude:
      - '%kernel.project_dir%/src/Shared/Domain/'
      - '%kernel.project_dir%/src/Shared/UI/Resources/'

  App\Shared\Domain\Bus\Event\EventBus:
    class: App\Shared\Infrastructure\Bus\Event\InMemoryEventBus

  App\Shared\Domain\Bus\Command\CommandBus:
    class: App\Shared\Infrastructure\Bus\Command\InMemoryCommandBus

  App\Shared\Domain\Bus\Query\QueryBus:
    class: App\Shared\Infrastructure\Bus\Query\InMemoryQueryBus

doctrine:
  orm:
    mappings:
      App\Shared\Domain:
        is_bundle: false
        type: xml
        dir: '%kernel.project_dir%/src/Shared/Infrastructure/Persistence/Doctrine'
        prefix: 'App\Shared\Domain'
